# Generated by Django 2.2.4 on 2019-12-14 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191214_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, default=200, max_digits=20),
            preserve_default=False,
        ),
    ]
